# Generated by Django 5.2.4 on 2025-07-10 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_user',
            fields=[
                ('nickname', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar_image', models.ImageField(null=True, upload_to='C:\\Users\\arsyh\\photofeed\\photoforum\\avatar')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='feed_image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\arsyh\\photofeed\\photoforum\\image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.forum_user'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
