# Generated by Django 5.2.4 on 2025-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_forum_user_image_feed_image_alter_image_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='feed_image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\arsyh\\photofeed\\photoforum\\image'),
        ),
    ]
